### ISSUE TITLE
Event loop stuck

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-kubernetes#80] opened 2020-06-30 11:22 UTC
While testing #74 I managed to get IJ not responding at all because the AWT event loop was blocked.

Here is the stack trace:

Name: AWT-EventQueue-0
State: TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@55a5384e
Total blocked: 149  Total waited: 3 435

Stack trace: 
```
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:139)
io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:341)
io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:788)
io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:772)
io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:73)
org.jboss.tools.intellij.kubernetes.model.ResourceWatch.doWatch(ResourceWatch.kt:51)
org.jboss.tools.intellij.kubernetes.model.ResourceWatch.watchAll(ResourceWatch.kt:34)
org.jboss.tools.intellij.kubernetes.model.context.ActiveContext.startWatch(ActiveContext.kt:209)
org.jboss.tools.intellij.kubernetes.model.context.ActiveContext.setCurrentNamespace(ActiveContext.kt:94)
org.jboss.tools.intellij.kubernetes.model.ResourceModel.setCurrentNamespace(ResourceModel.kt:68)
org.jboss.tools.intellij.kubernetes.actions.UseProjectAction.actionPerformed(UseProjectAction.kt:22)
com.redhat.devtools.intellij.common.actions.TreeAction.actionPerformed(TreeAction.java:101)
com.redhat.devtools.intellij.common.actions.TreeAction.actionPerformed(TreeAction.java:95)
com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$$Lambda$1294/535469770.run(Unknown Source)
com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:277)
javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
com.intellij.openapi.actionSystem.impl.ActionMenuItem$$Lambda$1291/520830695.run(Unknown Source)
com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
com.intellij.openapi.application.TransactionGuardImpl$$Lambda$297/964995748.run(Unknown Source)
com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:522)
com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:544)
java.awt.Component.processMouseEvent(Component.java:6548)
javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
java.awt.Component.processEvent(Component.java:6313)
java.awt.Container.processEvent(Container.java:2237)
java.awt.Component.dispatchEventImpl(Component.java:4903)
java.awt.Container.dispatchEventImpl(Container.java:2295)
java.awt.Component.dispatchEvent(Component.java:4725)
java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
java.awt.Container.dispatchEventImpl(Container.java:2281)
java.awt.Window.dispatchEventImpl(Window.java:2746)
java.awt.Component.dispatchEvent(Component.java:4725)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
java.awt.EventQueue.access$500(EventQueue.java:98)
java.awt.EventQueue$3.run(EventQueue.java:715)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
java.awt.EventQueue$4.run(EventQueue.java:737)
java.awt.EventQueue$4.run(EventQueue.java:735)
java.security.AccessController.doPrivileged(Native Method)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by adietish** [comment] 2020-08-11 13:46
I didnt look into this in all details but I noticed this when looking into #49. This also happens when the server is not reachable (ex. minikube stopped). The effect is that ex. the context menu wont pop up.
I believe that this is caused by synchronous network calls (to the cluster) that are operated in the same thread as the one that builds the tree/UI. To fix this, I'd have to change resource retrieval from synchronous to non-synchronous calls

**Comment by adietish** [comment] 2020-08-19 10:25
With the PR for #49 in place, I'm not able to reproduce this with a minikube that's stopped. The tree starts loading once you unfold the cluster and displays "Loading..."
![image](https://user-images.githubusercontent.com/25126/90623445-c164fb80-e216-11ea-8eb2-ccd2e301ce6d.png)
While this is displayed IntelliJ stays absolutely responsive, I can switch views, edit files, etc.
After the request times out, the categories are displayed with errors reporting that the resources could not be retrieved.
@jeffmaury Can you confirm this or are things behaving differently for you?

**Comment by adietish** [comment] 2020-09-04 09:39
This is duplicate to #86. Closing.

**Closed by adietish** 2020-09-04 09:39 UTC
Labels: bug
