### ISSUE TITLE
Error when opening new plugin version

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-kubernetes#180] opened 2021-03-29 13:10 UTC
duplicate to #107 where this happened at runtime apparently.

This occurs with the new plugin released. When i open the plugin tab i get the error below. The tree is visible but it's like it misses something. E.g when you click on a project/namespace you don't have the action to switch.

![image](https://user-images.githubusercontent.com/49404737/112841258-90984f00-90a0-11eb-8511-ec9515ead378.png)

```
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.redhat.devtools.intellij.kubernetes.model.IModelChangeObservable (requestorClass=com.redhat.devtools.intellij.kubernetes.model.ResourceModel, requestorConstructor=public com.redhat.devtools.intellij.kubernetes.model.ResourceModel(com.redhat.devtools.intellij.kubernetes.model.IModelChangeObservable,com.redhat.devtools.intellij.kubernetes.model.IContexts)).

Probably constructor should be marked as NonInjectable. [Plugin: com.redhat.devtools.intellij.kubernetes]
	at com.intellij.serviceContainer.ConstructorParameterResolver.findTargetAdapter(ConstructorParameterResolver.kt:111)
	at com.intellij.serviceContainer.ConstructorParameterResolver.isResolvable(ConstructorParameterResolver.kt:39)
	at com.intellij.serviceContainer.ConstructorInjectionKt.getGreediestSatisfiableConstructor(constructorInjection.kt:106)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:36)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:288)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:18)
	at com.redhat.devtools.intellij.kubernetes.KubernetesToolWindowFactory.createTree(KubernetesToolWindowFactory.kt:41)
	at com.redhat.devtools.intellij.kubernetes.KubernetesToolWindowFactory.createToolWindowContent(KubernetesToolWindowFactory.kt:33)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:534)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.java:358)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel.contentManager(ContentTabLabel.java:356)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel.isSelected(ContentTabLabel.java:339)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel._getGraphics(ContentTabLabel.java:348)
	at com.intellij.openapi.wm.impl.content.BaseLabel.paintComponent(BaseLabel.java:78)
	at com.intellij.openapi.wm.impl.content.ContentTabLabel.paintComponent(ContentTabLabel.java:334)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.paintChildren(ToolWindowContentUi.java:262)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at com.intellij.openapi.wm.impl.ToolWindowHeader.paintChildren(ToolWindowHeader.java:249)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adietish** [comment] 2021-03-30 14:37
that's very odd, never seen this error and I dont know why/when this should happen. Googling showed a few issues in PyCharm where the advice was to clear the caches: File > Invalidate Caches/Restart
@jeffmaury any idea?

**Comment by adietish** [comment] 2021-03-30 14:48
[here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360005805879-PluginException-getComponentAdapterOfType-is-used-to-get-XXX-Probably-constructor-should-be-marked-as-NonInjectable-) the report suggests that this happens on classes with constructors that are only intended for testing:
> classes that trigger the exception indeed have a "non injectable", test-only constructor in addition to the one used by the platform DI.
But this isn't the case for the class it is complaining about which only has a non-arg, empty constructor:
```
open class ModelChangeObservable: IModelChangeObservable {
```

**Comment by adietish** [comment] 2021-03-30 15:10
Further up in the stack trace there's maybe the cause for this
```java
at com.redhat.devtools.intellij.kubernetes.KubernetesToolWindowFactory.createTree(KubernetesToolWindowFactory.kt:41)
```
which is the call to the following:
```
val resourceModel = ServiceManager.getService(IResourceModel::class.java)
```
which is matching the problem described above since ResourceModel has a constructor with arguments:
```kotlin
open class ResourceModel(
    private val observable: IModelChangeObservable = com.redhat.devtools.intellij.kubernetes.model.ModelChangeObservable(),
    private val contexts: IContexts = Contexts(observable, ::create)
) : IResourceModel {
```

**Comment by adietish** [comment] 2021-03-31 13:42
Here's another bug report that reports the same with an explanation:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006171500-PluginException-getComponentAdapterOfType-is-used-to-get-XXX-Probably-constructor-should-be-marked-as-NonInjectable-
>The problem is, we use overloaded package-private constructors for unit testing.
I am doing a similar thing, I provide a constructor with 2 arguments, both have default parameters. When looking at the generated bytecode this indeed creates 3 constructors:
* one with 2 parameters
```
  public <init>(Lcom/redhat/devtools/intellij/kubernetes/model/IModelChangeObservable;Lcom/redhat/devtools/intellij/kubernetes/model/IContexts;)V
```
* one with no parameters
```
  public <init>()V
```
* a syntetic constructor with 3 parameters (the 2 known parameters and a kotlin marker Defaultconstructor)
```
  public synthetic <init>(Lcom/redhat/devtools/intellij/kubernetes/model/IModelChangeObservable;Lcom/redhat/devtools/intellij/kubernetes/model/IContexts;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
```
So my guess is that I have to provide a constructor without parameters, initialize the 2 variables in fileds instead and override them in my test class.

**Comment by adietish** [comment] 2021-03-31 14:01
Interesting enough constructors that are marked as `@Deprecated` seem to be ignored by this check:
> 

It seems that classes that trigger the exception indeed have a "non injectable", test-only constructor in addition to the one used by the platform DI.
>
I suggest that constructors that bear the @com.google.common.annotations.VisibleForTesting annotation are excluded (like the @java.lang.Deprecated ones).

**Closed** 2021-03-31 17:23 UTC
Labels: bug, severity/critical
